os: Visual Studio 2015

platform:
  - x86
  - x64

# Install scripts. (runs after repo cloning)
install:
  # Init submodules
  - git submodule update --init --recursive


# Build it
build_script:
  - mkdir build
  - cd build
  - if "%platform%" == "x86" cmake ..
  - if "%platform%" == "x64" cmake .. -G"Visual Studio 14 Win64"
  - cmake --build .

test: off
